# Generated by Django 3.0.6 on 2020-06-04 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nivel',
            fields=[
                ('id_nivel', models.AutoField(primary_key=True, serialize=False)),
                ('nivel', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('usuario', models.CharField(max_length=50)),
                ('Tel', models.CharField(max_length=10)),
                ('pasword', models.CharField(max_length=20)),
                ('Fecha_Nacimiento', models.DateField()),
                ('id_nivel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='login.Nivel')),
            ],
        ),
        migrations.CreateModel(
            name='logeados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=50)),
                ('ingres', models.BooleanField()),
                ('hora_log', models.DateField()),
                ('id_nivel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='login.Nivel')),
            ],
        ),
    ]
